version: "3.9"

services:
  storage-service:
    image: goatprodhub/test-service:latest
    ports:
      - 8080:80 # Порт для доступа к приложению
    depends_on:
      mongo:
        condition: service_healthy # Ждем, пока Mongo будет готова
      redis:
        condition: service_healthy
    environment:
      - ENV=prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"] # Пинг здоровья приложения (предположим, что у тебя есть такой endpoint)
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storage-service.rule=Host(`storage-service-labs.traefik.me`)"
      - "traefik.http.routers.storage-service.entrypoints=websecure"
      - "traefik.http.routers.storage-service.tls.certResolver=letsencrypt"
      - "traefik.http.services.storage-service.loadbalancer.server.port=80"

  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017 # Порт для доступа к MongoDB
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"] # Проверка готовности Mongo
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379 # Порт Redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"] # Проверка готовности Redis
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
  dokploy-network:
    external: true
