# .github/workflows/docker-image.yml
name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Событие при пуше в master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build --platform linux/amd64 -t goatprodhub/storage-service:latest . 
          docker push goatprodhub/storage-service:latest
